### ISSUE TITLE
Temperature calculation ignores rtd_nominal for temperatures below zero

### ISSUE THREAD

**Issue by KlaasH** [adafruit/Adafruit_CircuitPython_MAX31865#11]
The above-zero calculation [uses `rtd_nominal`](https://github.com/adafruit/Adafruit_CircuitPython_MAX31865/blob/2.1.2/adafruit_max31865.py#L241) but [the below-zero calculation doesn't](https://github.com/adafruit/Adafruit_CircuitPython_MAX31865/blob/2.1.2/adafruit_max31865.py#L247-L258).  So if `rtd_nominal` is set to anything but 100, when the resistance drops below that value the reported temperature will abruptly jump to the uncalibrated value.

It seems like the below-zero formula is more complicated and it might not be feasible to incorporate `rtd_nominal` in it, but giving the wrong answer seems like a bad failure mode.  Either returning `None` or raising an exception in the case where `rtd_nominal` is overridden and the initial calculation is negative would seem better to me.

**Comment by kattni** [comment]
Fixed by #9
