### ISSUE TITLE
Reduce self-heating

### ISSUE THREAD

**Issue by ben-lewis** [adafruit/Adafruit_CircuitPython_MAX31865#22]
As with the equivalent C++ library https://github.com/adafruit/Adafruit_MAX31865, the bias current seems to be left on permanently, leading to increased self-heating. Adding self.bias = False at line 233 of adafruit_max31865.py should fix this. Also, maybe a note should be made that all improvements to C++ libraries should be duplicated in the equivalent python library and vice versa.

**Comment by ben-lewis** [comment]
#23

**Comment by jposada202020** [comment]
@ben-lewis Could this be closed now the changes were merged? thanks :)
