### ISSUE TITLE
Is the constant "_MAX31865_CONFIG_FILT60HZ" redundant?   

### ISSUE THREAD

**Issue by molcay** [adafruit/Adafruit_CircuitPython_MAX31865#24]
Hi, 
I was reading the code, and see that there is a variable called `_MAX31865_CONFIG_FILT60HZ`, then I search for usage of it and see nothing. As far as I see, there is an if-else statement in line [116-119](https://github.com/adafruit/Adafruit_CircuitPython_MAX31865/blob/master/adafruit_max31865.py#L116-L119). The 50Hz variable is using in both if and else blocks(in if block there is an OR(|) operator, in else block there are an AND(&) and a Complementary(~) operators):
```python
    if filter_frequency == 50:
        config |= _MAX31865_CONFIG_FILT50HZ
    else:
        config &= ~_MAX31865_CONFIG_FILT50HZ
```

I do not have any superior knowledge of this but it seems off. Maybe the else statement is wrong or the variable `_MAX31865_CONFIG_FILT60HZ` is redundant?

**Comment by ladyada** [comment]
yah you can only set either 50 or 60
![image](https://user-images.githubusercontent.com/1214161/99483596-8c0e9d80-292c-11eb-8df2-3b50051740c2.png)

is that what you mean?

**Comment by molcay** [comment]
Yeap, but I just want to point that there is a variable (called `_MAX31865_CONFIG_FILT60HZ `) definition in line [71](https://github.com/adafruit/Adafruit_CircuitPython_MAX31865/blob/master/adafruit_max31865.py#L71) but there is no usage of it(it may be redundant).

**Comment by caternuson** [comment]
Yah, it's not used. Since it can only be two values, the setting can be inferred: 
https://github.com/adafruit/Adafruit_CircuitPython_MAX31865/blob/e8dc04f7ff884afbafba6bf2b65c7b7fb0425bca/adafruit_max31865.py#L116-L119
It was probably defined with the intention that it be used, but then the actual code logic (above) did not actually end up needing it.
