### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by IronBamBam1990** [adafruit/Adafruit_CircuitPython_MAX31865#26]
How to loop a scrpit or file? I cant get loop so i must open and open file to check temp. I try loop it by systemd and other stuff like "import os" but its not working and issue with os is "no module called os" (raspberry). The worse thing is i try while true() in script but also not working so any ideas how to do loop ? My idea is: tomorrow i try with lcd to get temp on screen in loop.

**Comment by ladyada** [comment]
hi for project help use forums or discord
