### ISSUE TITLE
setters not working

### ISSUE THREAD

**Issue by laflaf3d** [adafruit/Adafruit_CircuitPython_MAX31865#28]
Hi, cause I need to test many MAX31865's features on RPI I use your library. I observe that with Python (3.7.3 in my case) I can't use bias and auto_conversion : setters doesn't work at all. After google search I found that the library is not well designed for Python 3.
I changed localy adafruit_max31865.py like that :
replacing "class MAX31865:" by "class MAX31865(object):"
It's work's now.
Best regards

**Comment by tannewt** [comment]
I think you are running python 2. `class MAX31865(object):` is a python 2 thing. In python 3, classes are new-style classes by default. How do you know you are running Python 3? You likely have both installed.

**Comment by laflaf3d** [comment]
Hi, thanks for your answer.
"python -V" command display "Python 3.7.3". When I launch my python's code, "print(sys.version)" display "Python 3.7.3 (default, Jul 25 2020, 13:03:44). But you're right, my way is not good. Bias's setter seems to not work only because Adafruit put it to False at the en of the read_rtd method. So when I set Bias at True, read a PT100 and get Bias, it appear False again.
By the way, it's strange to create setters if these variable are forced later in the code. And for me, this library doesn't work. To really work with, I just have to comment lines 209 and 216 (that put Bias at True and False) in read_rtd method and set bias and auto-convert by myself.

**Comment by tannewt** [comment]
@laflaf3d Ya, that seems like a bug. That code should read bias before saving it and then restore the value instead of false at the end.

**Comment by FoamyGuy** [comment]
resolved by #32
