### ISSUE TITLE
Getting output "-242.020C"

### ISSUE THREAD

**Issue by job1234** [adafruit/Adafruit_CircuitPython_MAX31865#37]
Hi,
When I run the sample code I always get this as output:
"Temperature: -242.020C
Temperature: -242.020C
Temperature: -242.020C
Temperature: -242.020C
Temperature: -242.020C
Temperature: -242.020C
Temperature: -242.020C
Temperature: -242.020C
Temperature: -242.020C
^CTraceback (most recent call last):
  File "/home/pi/tempsensor/Adafruit_CircuitPython_MAX31865/examples/max31865_simpletest.py", line 29, in <module>
    time.sleep(1.0)
KeyboardInterrupt"

I'm stuck with this and can't get it fixed.
When I type **ls -l /dev/spidev*** in the terminal I get this as output:
"crw-rw---- 1 root spi 153, 0 Mar 24 15:01 /dev/spidev0.0
crw-rw---- 1 root spi 153, 1 Mar 24 15:01 /dev/spidev0.1"

Does someone know what's wrong. Is my MAX31865 stuck or something?

**Comment by caternuson** [comment]
This could be hardware related. Please post in the forums with photos of your setup:
https://forums.adafruit.com/

**Comment by job1234** [comment]
![IMG_20220324_194153.jpg](https://user-images.githubusercontent.com/11525922/159997100-1c4e9f62-f2dd-4f77-b386-3b949e0ec962.jpg)
This is my setup. The connection to the Raspberry Pi is good. That's what I know.

**Comment by ladyada** [comment]
hi since that isnt a board that is made by us, it could be a hardware issue - please contact the seller you purchased it from first for tech support - they have engineers who can help you get it working!
