### ISSUE TITLE
Faster Temperature Measurement

### ISSUE THREAD

**Issue by zakidani** [adafruit/Adafruit_CircuitPython_MAX31865#7]
Hello !
I am using 3 Devices (Max31865) with Raspberry pi and in 1 second I get only 6 values from each sensor. 
If I use single device I get 14 values from sensor in 1 second. Is it possible to get values from sensors a bit faster say 20 values from each sensor in one second.
Guidance will be highly appericiated 

Regards
Danial

**Comment by ladyada** [comment]
no, there are delays required to let the values settle, RTDs are not fast sensors :) every time you request the temperature it will delay and wait and the library is not asyncronous at this time.
